---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pttg-rps-scheduler
  labels:
    version: {{.VERSION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pttg-rps-scheduler
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: pttg-rps-scheduler
        version: {{.VERSION}}
      annotations:
        pod.beta.kubernetes.io/init-containers: '
[
   {
      "name": "vaultjks",
      "image": "quay.io/ukhomeofficedigital/vaultjks:v0.1.0",
      "securityContext": {
         "capabilities": {
           "drop": [
             "SETUID",
             "SETGID"
           ]
         }
      },
      "imagePullPolicy": "Always",
      "env": [
         {
            "name": "VAULT_ADDR",
            "value": "https://vault.vault.svc.cluster.local:8200"
         },
         {
            "name": "VAULT_TOKEN",
            "valueFrom": {
               "secretKeyRef": {
                  "name": "store-token",
                  "key": "token"
               }
            }
         },
         {
            "name": "VAULT_PKI_PATH",
            "value": "services/pt-i-{{.ENVIRONMENT}}/pki"
         },
         {
            "name": "VAULT_ROLE_NAME",
            "value": "default"
         },
         {
            "name": "SLEEP_FOREVER",
            "value": "false"
         },
         {
            "name": "IP_SAN",
            "valueFrom": {
               "fieldRef": {
                  "apiVersion": "v1",
                  "fieldPath": "status.podIP"
               }
            }
         }
      ],
      "volumeMounts": [
         {
            "mountPath": "/data",
            "name": "javapki"
         }
      ]
   }
]
        '
    spec:
      imagePullSecrets:
      - name: registrykey
      containers:
      - name: pttg-rps-scheduler
        image: quay.io/ukhomeofficedigital/pttg-rps-scheduler:{{.VERSION}}
        securityContext:
           capabilities:
             drop:
               - SETUID
               - SETGID
        env:
          - name: JAVA_OPTS
            value: "-Xms150m -Xmx250m"
          - name: SERVER_PORT
            value: '8080'
          - name: ENDPOINTS_INFO_ENABLED
            value: 'false'
          - name: BASE_HMRC_ACCESS_CODE_URL
            value: 'https://pttg-ip-hmrc-access-code.pt-i-{{.ENVIRONMENT}}.svc.cluster.local'
          - name: JDK_TRUST_FILE
            value: '/data/truststore.jks'
          - name: REFRESH_INTERVAL
            valueFrom:
              configMapKeyRef:
                name: endpoint-config
                key: HMRC_ACCESS_CODE_REFRESH_INTERVAL
        resources:
          limits:
            cpu: 1600m
            memory: 612Mi
          requests:
            cpu: 100m
            memory: 484Mi
        ports:
          - name: http
            containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
            httpHeaders:
              - name: X-probe
                value: kubelet
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
            httpHeaders:
              - name: X-probe
                value: kubelet
          periodSeconds: 20
          timeoutSeconds: 5
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /data
            name: javapki
            readOnly: true
      volumes:
      - name: secrets
        emptyDir:
          medium: "Memory"
      - name: javapki
        emptyDir:
          medium: "Memory"
